# Generated by Django 4.1.2 on 2022-10-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "mood_score",
                    models.IntegerField(
                        choices=[
                            (0, "Black"),
                            (1, "Red"),
                            (2, "Orange"),
                            (3, "Yellow"),
                            (4, "Green"),
                            (5, "Blue"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.calendar",
                    ),
                ),
            ],
        ),
    ]
